@baseURL = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json

{
    "name": "Fernando Duru",
    "phone": "11975775215",
    "email": "fernandoduru@gmail.com",
    "password": "123456", 
    "passwordConfirmation": "123456"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
    "email": "fernandoduru@gmail.com",
    "password": "123456"
}

###

# @name category
POST {{baseURL}}/categories
Content-Type: application/json

{
    "title": "Imóvel"
}

###

# @name product
POST {{baseURL}}/products
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Mesa",
    "description": "Mesa 120cm redonda com 4 cadeiras",
    "categoryId": "3b895ca4-a022-4058-a252-bf3038118f75",
    "priceInCents": 159999
}

###

# @name fetch_product
GET {{baseURL}}/products?page=1&q=
Content-Type: application/json
Authorization: Bearer {{authToken}}

{

}

###

