version: '3.8'

services:
  postgres:
    container_name: marketplace-pg
    image: bitnami/postgresql
    ports:
      - 5433:5433
    environment:
      - POSTGRESQL_DATABASE=marketplace
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_PORT_NUMBER=5433
    volumes:
      - ./data/pg:/data/postgres

  # cache: 
  #   container_name: nest-clean-cache
  #   image: redis
  #   ports: 
  #     - 6379:6379
  #   volumes:
  #     - ./data/redis:/data
